### ISSUE TITLE
What is meant here -- the Slurm database or slurmdbd?

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-hpc#16]
@mslacken @e4t Could you take a look at this line and check whether this is supposed to mean the Slurm database or slurmdbd?

The original wording had the clearly typo'd `slurmbd` [note the position of `b` and `d`], this was changed to `slurmdb` since, but I am not sure that that change was correct.

### Current version
https://github.com/SUSE/doc-hpc/blob/6b585df94ce7d4882a8c113980a0d9de172e2645/xml/slurm.xml#L794-L797

### Original version with slurmbd typo
https://github.com/SUSE/doc-hpc/blob/38b318372d061d0ff348cf1bcfa9c17fec6d95f1/xml/slurm.xml#L1027-L1031

**Comment by mslacken** [comment]
The slurm database daemon is `slurmdbd`, `slurmdb` must have been a typo

**Comment by sknorr** [comment]
Thank you! Fixed.

**Comment by e4t** [comment]
The entire sentence is unclear. The [slurm release notes ](https://elwe.rhrk.uni-kl.de/documentation/news.html)
state: 
_NOTE: If using a backup DBD you must start the primary first to do any
database conversion, the backup will not start until this has happened._
Thus, the paragraph should read:
 &lt;note&gt;
   &lt;title&gt;Convert primary slurmdbd first&lt;/title&gt;
                &lt;para&gt; 
If a backup database daemon is used, the primary one needs to be
                 upgraded and run to perform the conversion first. The backup will not start until this has happened.
                &lt;/para&gt;
               &lt;/<span class="pl-ent">note</span>&gt;
This explains the precisely.

**Comment by e4t** [comment]
Note that this should be in the part shared with the release notes, so it needs to be copied to all versions of these.
