### ISSUE TITLE
Take commits from `master` branch

### ISSUE THREAD

**Issue by sknorr** [SUSE/doc-hpc#22]
@lproven It appears that Egbert accidentally pushed three commits to a (newly-created) master branch some time in April. Could you check whether these commits are still relevant for main? (If you have time.)

Specifically, this is about the following commits: bc72357cc / 0354ed33 / b85e09ec9c

**Comment by lproven** [comment]
Good find -- thank you.

These are now in https://github.com/SUSE/doc-hpc/pull/23
