### ISSUE TITLE
Technical reference/developer guide?

### ISSUE THREAD

**Issue by tahliar** [SUSE/doc-hpc#40]
Would it make sense to move the "HPC user libraries" chapter (and maybe also the spack chapter) to a separate guide called Technical Reference or Developer Guide or something similar?

**Comment by aginies** [comment]
this is part of the product now, without spack you dont have so much hpc libs avaialble, so we should probably keep it in the official guide

**Comment by tahliar** [comment]
Thanks, closing this issue then.
