### ISSUE TITLE
How to know the new version of slurm to upgrade to?

### ISSUE THREAD

**Issue by tahliar** [SUSE/doc-hpc#45]
@mslacken @e4t The documented command to upgrade slurm is `zypper install --force-resolution slurm_VERSION`, e.g. `slurm_20_11`. This means you need to know the version number to include it in the command.

How does the admin find out what the new version number is? From update advisories? Or is there a search command you can run to find out?

**Comment by aginies** [comment]
You can get the version of slurm packages using SCC, or using zypper: zypper -v slurm

**Comment by tahliar** [comment]
Thanks!
